export const SITE = {
  name: 'Eng-Mart',
  tagline: 'Premium Industrial Electrical Products',
  description: 'Pakistan\'s premier supplier of industrial electrical equipment — MCBs, MCCBs, Contactors, CTs, Panel Meters and more from world-class brands.',
  phone: '+92-21-32763951',
  mobile: '+92-311-2763951',
  email: 'info@eng-mart.com',
  address: 'Shop No. 5, Pak Chamber, Sarafa Bazar, Karachi, Pakistan',
  hours: 'Mon–Sat: 9:00 AM – 7:00 PM',
  whatsapp: '+92-311-2763951',
  url: 'https://eng-mart.com',
}

export const BRANDS = [
  { name: 'ABB', slug: 'abb', country: 'Switzerland', supplier: 'Ameejee Valleejee & Sons', color: '#FF0000', products: 180, icon: 'Zap' },
  { name: 'CHINT', slug: 'chint', country: 'China', supplier: 'HL PK Pvt Ltd', color: '#0066CC', products: 220, icon: 'Layers' },
  { name: 'Himel', slug: 'himel', country: 'International', supplier: 'Powerhouse', color: '#E30613', products: 310, icon: 'ShieldAlert' },
  { name: 'FICO Hi-Tech', slug: 'fico', country: 'Pakistan', supplier: 'Cognitive Solutions', color: '#1B4F8A', products: 260, icon: 'Gauge' },
  { name: 'PCE', slug: 'pce', country: 'Germany', supplier: 'Powerhouse', color: '#F97316', products: 90, icon: 'Plug' },
  { name: 'Tense', slug: 'tense', country: 'Turkey', supplier: 'AT Electricals', color: '#C0392B', products: 150, icon: 'Activity' },
  { name: 'Kondas', slug: 'kondas', country: 'Turkey', supplier: 'AT Electricals', color: '#2980B9', products: 45, icon: 'Cpu' },
  { name: 'Opas', slug: 'opas', country: 'Turkey', supplier: 'AT Electricals', color: '#27AE60', products: 60, icon: 'Sliders' },
]

export const CATEGORIES = [
  {
    name: 'Miniature Circuit Breakers',
    short: 'MCBs',
    slug: 'mcb',
    icon: '⚡',
    description: '1-Pole to 4-Pole MCBs, 4.5kA to 10kA breaking capacity, B/C/D curves from ABB, CHINT & Himel',
    brands: ['ABB', 'CHINT', 'Himel'],
    count: 120,
    color: '#F97316',
  },
  {
    name: 'Molded Case Circuit Breakers',
    short: 'MCCBs',
    slug: 'mccb',
    icon: '🔌',
    description: 'Fixed & adjustable MCCBs from 16A to 1600A, 25kA to 70kA from ABB, CHINT & Himel',
    brands: ['ABB', 'CHINT', 'Himel'],
    count: 180,
    color: '#1E3A5F',
  },
  {
    name: 'Magnetic Contactors',
    short: 'Contactors',
    slug: 'contactors',
    icon: '🔧',
    description: '3-Pole & 4-Pole contactors from 9A to 750A, 4kW to 400kW motor ratings',
    brands: ['ABB', 'CHINT', 'Himel'],
    count: 95,
    color: '#0F4C81',
  },
  {
    name: 'Current Transformers',
    short: 'CTs',
    slug: 'current-transformers',
    icon: '🔄',
    description: 'Window, split-core, resin-cast & bar-type CTs, 30/5A to 8000/5A, Class 0.5 to 1',
    brands: ['FICO Hi-Tech', 'Himel'],
    count: 210,
    color: '#7C3AED',
  },
  {
    name: 'Digital & Analogue Meters',
    short: 'Panel Meters',
    slug: 'panel-meters',
    icon: '📊',
    description: 'Voltmeters, ammeters, frequency, watt & multifunction panel meters — 48mm to 96mm',
    brands: ['Tense', 'FICO Hi-Tech', 'Himel'],
    count: 140,
    color: '#0891B2',
  },
  {
    name: 'Power Capacitors & PF Controllers',
    short: 'Capacitors',
    slug: 'capacitors',
    icon: '⚙️',
    description: 'Dry-type LV capacitors 2.5 to 50 KVAR, 415-440VAC, PF controllers 6 to 12 stage',
    brands: ['Kondas', 'Tense', 'ABB', 'Himel'],
    count: 55,
    color: '#059669',
  },
  {
    name: 'Industrial Sockets & Plugs',
    short: 'Industrial Plugs',
    slug: 'industrial-sockets',
    icon: '🔌',
    description: 'IP44 & IP67 industrial sockets and plugs, 16A to 125A, 3-Pole & 5-Pole — PCE brand',
    brands: ['PCE'],
    count: 90,
    color: '#DC2626',
  },
  {
    name: 'Protection Relays',
    short: 'Protection Relays',
    slug: 'protection-relays',
    icon: '🛡️',
    description: 'Under/over voltage, phase failure, phase monitoring relays from Tense & Himel',
    brands: ['Tense', 'Himel', 'ABB'],
    count: 45,
    color: '#B45309',
  },
  {
    name: 'Cam & Selector Switches',
    short: 'Cam Switches',
    slug: 'cam-switches',
    icon: '🎛️',
    description: '2/3/4-Pole changeover & phase selector cam switches 32A to 315A — Opas brand',
    brands: ['Opas', 'FICO Hi-Tech'],
    count: 60,
    color: '#6D28D9',
  },
  {
    name: 'Variable Frequency Drives',
    short: 'VFDs',
    slug: 'vfd',
    icon: '📡',
    description: 'Basic to expert VFDs 0.75kW to 22kW for motor speed control — CHINT & Himel',
    brands: ['CHINT', 'Himel'],
    count: 35,
    color: '#0369A1',
  },
  {
    name: 'Air Circuit Breakers',
    short: 'ACBs',
    slug: 'acb',
    icon: '⚡',
    description: 'Fixed & draw-out ACBs 800A to 6300A, 42kA to 100kA — ABB E-Series & Himel',
    brands: ['ABB', 'Himel'],
    count: 42,
    color: '#991B1B',
  },
  {
    name: 'HRC Fuses & Fuse Bases',
    short: 'HRC Fuses',
    slug: 'hrc-fuses',
    icon: '🔑',
    description: 'HRC fuse links & bases 10A to 630A, 11KV fuse links & D-type fuse fittings',
    brands: ['FICO Hi-Tech', 'Himel'],
    count: 70,
    color: '#065F46',
  },
  {
    name: 'Wiring Devices',
    short: 'Wiring Devices',
    slug: 'wiring-devices',
    icon: '🏠',
    description: 'Premium flush switches, 13A/15A sockets, USB outlets, fan dimmers — Himel Prime Series',
    brands: ['Himel'],
    count: 80,
    color: '#1D4ED8',
  },
  {
    name: 'Timers, Controls & Safety',
    short: 'Timers & Controls',
    slug: 'timers-controls',
    icon: '⏱️',
    description: 'Star-delta timers, on-delay, programmable timers, temperature controllers & liquid level relays',
    brands: ['Tense', 'Himel', 'ABB'],
    count: 55,
    color: '#7E22CE',
  },
]

export const FEATURED_PRODUCTS = [
  {
    name: 'CHINT NXB-63 MCB',
    slug: 'chint-nxb63-mcb',
    brand: 'CHINT',
    category: 'MCBs',
    catNo: 'NXB-63',
    description: '1-Pole MCB, C-Curve, 6kA Breaking Capacity, 6A–63A',
    specs: ['1P / 2P / 3P / 4P', '6kA Breaking Capacity', 'C-Curve', '6A to 63A'],
    badge: 'Best Seller',
    badgeColor: '#F97316',
  },
  {
    name: 'ABB SH201 MCB',
    slug: 'abb-sh201-mcb',
    brand: 'ABB',
    category: 'MCBs',
    catNo: 'SH201-C16',
    description: '1-Pole MCB, C-Curve, 6kA, 1A–40A — Swiss Quality',
    specs: ['1P / 2P / 3P / 4P', '6kA Breaking Capacity', 'C-Curve', '1A to 40A'],
    badge: 'Premium',
    badgeColor: '#1E3A5F',
  },
  {
    name: 'Himel HDM3 MCCB',
    slug: 'himel-hdm3-mccb',
    brand: 'Himel',
    category: 'MCCBs',
    catNo: 'HDM3-125',
    description: '3-Pole MCCB Fixed, 16A–1250A, 25kA–45kA Breaking Capacity',
    specs: ['3P & 4P Available', '25kA–45kA', 'Fixed & Adjustable', '16A to 1250A'],
    badge: 'Popular',
    badgeColor: '#059669',
  },
  {
    name: 'FICO ELC Current Transformer',
    slug: 'fico-elc-ct',
    brand: 'FICO Hi-Tech',
    category: 'Current Transformers',
    catNo: 'ELC-60',
    description: 'Window CT 60mm, Class 1, 100/5A to 1500/5A — Pakistan Made',
    specs: ['Class 1 Accuracy', '60mm Window', '15VA Burden', '100/5A–1500/5A'],
    badge: 'Local Brand',
    badgeColor: '#7C3AED',
  },
  {
    name: 'Tense DJA-96 Ammeter',
    slug: 'tense-dja96-ammeter',
    brand: 'Tense',
    category: 'Panel Meters',
    catNo: 'DJA-96',
    description: 'Digital AC Ammeter, 96x96mm, Made in Turkey — 3-Phase Available',
    specs: ['96x96mm Panel Size', 'Single & 3-Phase', 'LED Display', 'Made in Turkey'],
    badge: 'Turkish Made',
    badgeColor: '#C0392B',
  },
  {
    name: 'ABB AX-Series Contactor',
    slug: 'abb-ax-contactor',
    brand: 'ABB',
    category: 'Contactors',
    catNo: 'AX09-30-10',
    description: '3-Pole AC Contactor, 9A–475A, 4kW–250kW Motor Rating',
    specs: ['9A to 475A', '4kW to 250kW', '3-Pole & 4-Pole', 'IEC/UL Rated'],
    badge: 'Swiss Grade',
    badgeColor: '#1E3A5F',
  },
  {
    name: 'PCE Industrial Socket',
    slug: 'pce-industrial-socket',
    brand: 'PCE',
    category: 'Industrial Sockets',
    catNo: 'IP44-16A-3P',
    description: 'Wall Socket 16A 3-Pole, IP44 Protection, Blue — German Engineering',
    specs: ['IP44 / IP67', '16A to 125A', '3-Pole & 5-Pole', 'IEC 60309'],
    badge: 'IP67 Available',
    badgeColor: '#F97316',
  },
  {
    name: 'Kondas ZNPP Capacitor',
    slug: 'kondas-znpp-capacitor',
    brand: 'Kondas',
    category: 'Capacitors',
    catNo: 'ZNPP-25',
    description: 'Box Type Dry LV Capacitor, 25 KVAR, 440VAC, Made in Turkey',
    specs: ['5–50 KVAR Range', '440VAC', 'Box Type', 'Dry Type'],
    badge: 'Turkish Made',
    badgeColor: '#2980B9',
  },
  {
    name: 'Tense Protection Relay',
    slug: 'tense-protection-relay',
    brand: 'Tense',
    category: 'Protection Relays',
    catNo: 'PR-100',
    description: 'Under/over voltage, phase failure relay',
    specs: ['Under/Over Voltage', 'Phase Failure', 'Adjustable', 'Din Rail'],
    badge: 'Popular',
    badgeColor: '#B45309',
  },
  {
    name: 'Opas Cam Switch',
    slug: 'opas-cam-switch',
    brand: 'Opas',
    category: 'Cam Switches',
    catNo: 'CS-32',
    description: '3-Pole Phase Selector Cam Switch 32A',
    specs: ['3-Pole', '32A', 'Phase Selector', 'Panel Mount'],
    badge: 'New',
    badgeColor: '#6D28D9',
  },
  {
    name: 'CHINT VFD Drive',
    slug: 'chint-vfd',
    brand: 'CHINT',
    category: 'VFDs',
    catNo: 'VFD-11K',
    description: '11kW 3-Phase Variable Frequency Drive',
    specs: ['11kW', '3-Phase', 'Vector Control', 'Modbus'],
    badge: 'Smart',
    badgeColor: '#0369A1',
  },
  {
    name: 'ABB E-Max ACB',
    slug: 'abb-emax-acb',
    brand: 'ABB',
    category: 'ACBs',
    catNo: 'EX-1200',
    description: '1200A Draw-out Air Circuit Breaker',
    specs: ['1200A', 'Draw-out', '100kA', 'Smart Trip'],
    badge: 'Premium',
    badgeColor: '#991B1B',
  },
  {
    name: 'FICO HRC Fuse',
    slug: 'fico-hrc-fuse',
    brand: 'FICO Hi-Tech',
    category: 'HRC Fuses',
    catNo: 'HF-100',
    description: '100A High Rupturing Capacity Fuse Link',
    specs: ['100A', '500V', 'High Rupturing', 'Ceramic'],
    badge: 'Local Brand',
    badgeColor: '#065F46',
  },
  {
    name: 'Himel Wall Socket',
    slug: 'himel-wall-socket',
    brand: 'Himel',
    category: 'Wiring Devices',
    catNo: 'HW-13A',
    description: '13A Universal Wall Socket with Switch',
    specs: ['13A', 'Universal', 'Neon Indicator', 'Flame Retardant'],
    badge: 'Best Seller',
    badgeColor: '#1D4ED8',
  },
  {
    name: 'Tense Star-Delta Timer',
    slug: 'tense-star-delta-timer',
    brand: 'Tense',
    category: 'Timers & Controls',
    catNo: 'SD-T1',
    description: 'Adjustable Star-Delta Motor Control Timer',
    specs: ['Star-Delta', 'Adjustable', 'Din Rail', 'Turkey Made'],
    badge: 'Reliable',
    badgeColor: '#7E22CE',
  },
]

export const ALL_PRODUCTS = [
  ...FEATURED_PRODUCTS,
  ...FEATURED_PRODUCTS.map(p => ({ ...p, slug: p.slug + '-2', name: p.name + ' (Variant 2)' })),
  ...FEATURED_PRODUCTS.map(p => ({ ...p, slug: p.slug + '-3', name: p.name + ' (Premium)' })),
]

export const STATS = [
  { value: 8, suffix: '', label: 'Global Brands', description: 'Premium international brands' },
  { value: 2500, suffix: '+', label: 'Products', description: 'Across all categories' },
  { value: 14, suffix: '', label: 'Categories', description: 'Industrial product categories' },
  { value: 500, suffix: '+', label: 'Clients', description: 'Trusted across Pakistan' },
]

export const SERVICES = [
  {
    icon: '🏭',
    title: 'Industrial Supply',
    description: 'Complete range of industrial electrical equipment from switchgear to panel accessories for manufacturing plants and commercial buildings.',
  },
  {
    icon: '📋',
    title: 'Technical Consultation',
    description: 'Expert guidance on product selection, specifications, and sizing for your specific industrial applications and electrical panel requirements.',
  },
  {
    icon: '🚚',
    title: 'Karachi Delivery',
    description: 'Fast and reliable delivery across Karachi. Same-day dispatch on stocked items. Bulk order discounts available.',
  },
  {
    icon: '📄',
    title: 'Datasheets & Quotes',
    description: 'Detailed technical datasheets, competitive pricing, and formal quotations for procurement and tendering processes.',
  },
  {
    icon: '🔧',
    title: 'Custom Panel Builds',
    description: 'We supply all components for custom MCC panels, distribution boards, and control panels — one-stop sourcing.',
  },
  {
    icon: '🛡️',
    title: 'Warranty & Support',
    description: 'Manufacturer warranty on all products. Technical support and after-sales service from our experienced team.',
  },
]

export const WHY_CHOOSE = [
  { icon: '✅', title: 'Genuine Products', description: 'All products are 100% genuine from authorized distributors. No counterfeits.' },
  { icon: '🌍', title: '8 Global Brands', description: 'ABB, CHINT, Himel, FICO, PCE, Tense, Kondas, Opas — all under one roof.' },
  { icon: '⚡', title: 'Fast Availability', description: 'Large stock maintained for fast-moving items. Ready for immediate dispatch.' },
  { icon: '💰', title: 'Competitive Pricing', description: 'Best market prices on all brands. Volume discounts for contractors & panel builders.' },
  { icon: '📞', title: 'Expert Support', description: 'Our technical team helps you select the right product for your application.' },
  { icon: '📍', title: 'Karachi Based', description: 'Conveniently located in Sarafa Bazar, Karachi. Walk-in welcome Mon–Sat.' },
]

export const TESTIMONIALS = [
  {
    name: 'Engr. Kamran Ahmed',
    role: 'Electrical Contractor',
    company: 'KA Electrical Works',
    text: 'Eng-Mart has been our go-to supplier for ABB and CHINT products for years. Genuine products, competitive prices, and fast delivery. Highly recommended for panel builders.',
    rating: 5,
  },
  {
    name: 'M. Rashid Siddiqui',
    role: 'Procurement Manager',
    company: 'National Industrial Corp',
    text: 'We source all our Himel MCCBs and contactors from Eng-Mart. Their technical team helped us spec the right breaking capacity for our factory upgrade. Excellent service.',
    rating: 5,
  },
  {
    name: 'Asim Malik',
    role: 'Electrical Engineer',
    company: 'Malik Electrical Solutions',
    text: 'The FICO current transformers from Eng-Mart are high quality and WAPDA approved. Good stock availability and they provide datasheets. Will keep ordering from them.',
    rating: 5,
  },
  {
    name: 'Tariq Mehmood',
    role: 'Panel Builder',
    company: 'TM Engineering',
    text: 'From PCE industrial sockets to Tense digital meters — Eng-Mart has everything for MCC panel builds. Great pricing on Kondas capacitors too. Very professional team.',
    rating: 5,
  },
]

export const ANNOUNCEMENTS = [
  '🔥 New Stock Arrived: ABB TMAX MCCB Series — Contact for Pricing',
  '⚡ CHINT NXB-63 MCBs — Bulk Discounts Available',
  '🛡️ FICO Hi-Tech CTs — WAPDA & KE Approved Stock Ready',
  '📦 Free Delivery on Orders Above PKR 50,000 in Karachi',
  '🌟 Himel Wiring Devices Prime Series — Now In Stock',
]
